// Collaborative Network Music (workshop) led by Alo Allik (alo@tehis.net) and Anna Xambó (axambo@qmul.ac.uk).
// April 7-8, 2018.
// Organized by Music Hackspace.
// Sponsored by Rewire 2018. The Hague, The Netherlands.

// NETWORKING ACTIVITIES


// ANNA FREESOUND




// Parallel (Anna's Freesound live coding stuff')



// Pairs or small groups exchange




// Everyone controls central server




// Plan for performance
